version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: burnafterit-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://frontend
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - burnafterit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/utils/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: burnafterit-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_APP_URL=http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - burnafterit-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  burnafterit-network:
    driver: bridge
